### PR TITLE
Fluent bit

### PR DESCRIPTION
**Pull request by webwurst**
Add fluent-bit including Kubernetes metadata

### CODE REVIEW

**Comment by webwurst** [comment]
@puja108 can you check this out and give `./simple.t` according to the readme in the test-folder a try? please ping me for questions.

**Comment by webwurst** [comment]
@puja108 can you give this another try?
i think the three log-shippers are fine now.
tests with minikube doesnt't work that reliable, because of dns-problems there. i don't get these with `kubeadm-dind`. so maybe we could handle that in follow up issues.

**Comment by puja108** [comment]
ack, will try with kubeadm-dind

**Comment by webwurst** [comment]
you should also be able to try this on any test-cluster :smile: just provide the right context-name: `context=dind ./simple.t`

**Pull request merged**
