### PR TITLE
adding curator for cleanup

### PR DESCRIPTION
**Pull request by puja108**
with curator we can get some cleanup of old indexes implemented.

I guess implementing this as a scheduled job will be the way to go

### CODE REVIEW

**Comment by webwurst** [comment]
`ScheduledJobs` didn't work for my yet. Until the we should workaround using a `sleep-loop` deployment.

**Comment by puja108** [comment]
also good

**Comment by puja108** [comment]
tested in minikube, now need to either get it working as a Scheduled Job or using `sleep-loop`

@webwurst WDYT of deleting older than 3 days? too much? too few?

**Comment by webwurst** [comment]
Three days is fine as a default for a demo cluster, I guess. Just document how to change that value.

**Comment by puja108** [comment]
RFR @webwurst 

WFM on minikube (and I think on l8)

**Comment by webwurst** [comment]
not tested myself, but LGTM

**Comment by puja108** [comment]
With our fixes from last night, this should now also work on our clusters

**Pull request merged**
