### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by webwurst**
Works for me :tm:
This updates versions all over the place and also aligns directory structure with our other recipes.

### CODE REVIEW

**Comment by puja108** [comment]
What does the eventrouter do? Can we test on l8 before merging? Otherwise LGTM

**Comment by webwurst** [comment]
It is form here: https://github.com/heptio/eventrouter

But in early stage, so fine to leave it out for now.

**Comment by webwurst** [comment]
@puja108 removed eventrouter. will put it in a [wip] branch for now.

**Comment by puja108** [comment]
that was not what I meant, I just wanted to know what it does, it does sound cool, so leave it in 😉

**Comment by webwurst** [comment]
Ok, fine, may I merge now? ;)

**Comment by puja108** [comment]
I'd feel better if we'd tested it on l8 (feel free to wipe some stuff there) as l8 is most similar to what customers and test users are getting and they'll try to deploy this on their clusters (we're giving out some clusters soon again), would be bad if we break their experience.

**Comment by webwurst** [comment]
Tested is.

**Pull request merged**
